# Generated by Django 3.0.1 on 2020-01-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(default='leggings', max_length=20)),
                ('cloth_image', models.ImageField(upload_to='pics')),
                ('cloth_color', models.CharField(choices=[('GREY', 'Grey'), ('BLACK', 'Black'), ('YELLOW', 'Yellow'), ('RED', 'Red'), ('WHITE', 'White'), ('GREEN', 'Green'), ('ORANGE', 'Orange'), ('BLUE', 'Blue'), ('BROWN', 'Brown'), ('PINK', 'Pink')], default='RED', max_length=10)),
                ('cloth_price', models.CharField(max_length=20)),
                ('cloth_offer', models.CharField(max_length=20)),
                ('cloth_size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medim'), ('LARGE', 'LARGE'), ('X LARGEL', 'X-large'), ('XX LARGE', 'XX-large')], default='SMALL', max_length=10)),
            ],
        ),
    ]
