# Generated by Django 3.0.1 on 2020-01-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
